apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: experiment
spec:
  destination:
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: examples/experiment
    repoURL: 'https://github.com/ninyodios/rollouts-demo.git'
    targetRevision: HEAD
  project: demo
